### ISSUE TITLE
为何老是module loaded failed

### ISSUE THREAD

**Issue by Ive20** [wangzailfm/ScanLogin#2]
一加3 android7.1 xpose88.2 一直module loaded failed.  另外的xpose插件可以正常运行.

**Comment by wangzailfm** [comment]
可以将xposed的日志发给我

**Comment by Ive20** [comment]
05-22 22:09:33.345 I/Xposed  (  843): -----------------
05-22 22:09:33.345 I/Xposed  (  843): Starting Xposed version 88.2, compiled for SDK 25
05-22 22:09:33.345 I/Xposed  (  843): Device: ONEPLUS A3000 (OnePlus), Android version 7.1.1 (SDK 25)
05-22 22:09:33.345 I/Xposed  (  843): ROM: ONEPLUS A3000_16_170918
05-22 22:09:33.345 I/Xposed  (  843): Build fingerprint: OnePlus/OnePlus3/OnePlus3:7.1.1/NMF26F/08242149:user/release-keys
05-22 22:09:33.345 I/Xposed  (  843): Platform: arm64-v8a, 64-bit binary, system server: yes
05-22 22:09:33.345 I/Xposed  (  843): SELinux enabled: yes, enforcing: yes
05-22 22:09:34.372 I/Xposed  (  843): -----------------
05-22 22:09:34.372 I/Xposed  (  843): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
05-22 22:09:35.341 I/Xposed  (  843): Detected ART runtime
05-22 22:09:35.354 I/Xposed  (  843): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
05-22 22:09:35.656 I/Xposed  (  843): Loading modules from /data/app/com.oasisfeng.google.maps.rectify-1/base.apk
05-22 22:09:35.673 I/Xposed  (  843):   Loading class com.oasisfeng.google.maps.rectify.GoogleMapsXposed
05-22 22:09:35.675 I/Xposed  (  843): Loading modules from /data/app/com.android.vending.billing.InAppBillingService.LOCK-1/base.apk
05-22 22:09:35.709 I/Xposed  (  843):   Loading class com.chelpus.XSupport
05-22 22:09:35.721 E/Xposed  (  843):     Failed to load class com.chelpus.XSupport
05-22 22:09:35.721 E/Xposed  (  843): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: java.util.jar.JarVerifier$VerifierEntry
05-22 22:09:35.721 E/Xposed  (  843): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
05-22 22:09:35.721 E/Xposed  (  843): 	at com.chelpus.XSupport.initZygote(XSupport.java:65)
05-22 22:09:35.721 E/Xposed  (  843): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:552)
05-22 22:09:35.721 E/Xposed  (  843): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:466)
05-22 22:09:35.721 E/Xposed  (  843): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:96)
05-22 22:09:35.721 E/Xposed  (  843): Caused by: java.lang.ClassNotFoundException: java.util.jar.JarVerifier$VerifierEntry
05-22 22:09:35.721 E/Xposed  (  843): 	at java.lang.Class.classForName(Native Method)
05-22 22:09:35.721 E/Xposed  (  843): 	at java.lang.Class.forName(Class.java:400)
05-22 22:09:35.721 E/Xposed  (  843): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
05-22 22:09:35.721 E/Xposed  (  843): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
05-22 22:09:35.721 E/Xposed  (  843): 	... 4 more
05-22 22:09:35.721 E/Xposed  (  843): Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.jar.JarVerifier$VerifierEntry" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
05-22 22:09:35.721 E/Xposed  (  843): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-22 22:09:35.721 E/Xposed  (  843): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
05-22 22:09:35.721 E/Xposed  (  843): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-22 22:09:35.721 E/Xposed  (  843): 	... 8 more
05-22 22:09:35.721 I/Xposed  (  843): Loading modules from /data/app/com.fkzhang.wechatxposed-1/base.apk
05-22 22:09:35.752 I/Xposed  (  843):   Loading class com.fkzhang.wechatxposed.XposedInit
05-22 22:09:35.754 I/Xposed  (  843): Loading modules from /data/app/top.jowanxu.scanlogin-1/base.apk
05-22 22:09:35.778 I/Xposed  (  843):   Loading class top.jowanxu.scanlogin.Tutorial
05-22 22:09:35.779 E/Xposed  (  843):     Failed to load class top.jowanxu.scanlogin.Tutorial
05-22 22:09:35.779 E/Xposed  (  843): java.lang.ClassNotFoundException: Didn't find class "top.jowanxu.scanlogin.Tutorial" on path: DexPathList[[zip file "/data/app/top.jowanxu.scanlogin-1/base.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
05-22 22:09:35.779 E/Xposed  (  843): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-22 22:09:35.779 E/Xposed  (  843): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
05-22 22:09:35.779 E/Xposed  (  843): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-22 22:09:35.779 E/Xposed  (  843): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:536)
05-22 22:09:35.779 E/Xposed  (  843): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:466)
05-22 22:09:35.779 E/Xposed  (  843): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:96)
05-22 22:09:35.779 I/Xposed  (  843): Loading modules from /data/app/com.sinpo.nfcspy-1/base.apk
05-22 22:09:35.813 I/Xposed  (  843):   Loading class com.sinpo.nfcspy.XposedModApduRouting
11-03 12:23:37.925 I/Xposed  (  844): -----------------
11-03 12:23:37.925 I/Xposed  (  844): Starting Xposed version 88.2, compiled for SDK 25
11-03 12:23:37.925 I/Xposed  (  844): Device: ONEPLUS A3000 (OnePlus), Android version 7.1.1 (SDK 25)
11-03 12:23:37.925 I/Xposed  (  844): ROM: ONEPLUS A3000_16_170918
11-03 12:23:37.925 I/Xposed  (  844): Build fingerprint: OnePlus/OnePlus3/OnePlus3:7.1.1/NMF26F/08242149:user/release-keys
11-03 12:23:37.925 I/Xposed  (  844): Platform: arm64-v8a, 32-bit binary, system server: no
11-03 12:23:37.925 I/Xposed  (  844): SELinux enabled: yes, enforcing: yes
11-03 12:23:37.928 I/Xposed  (  844): -----------------
11-03 12:23:37.928 I/Xposed  (  844): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-03 12:23:38.407 I/Xposed  (  844): Detected ART runtime
11-03 12:23:38.415 I/Xposed  (  844): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-03 12:23:38.647 I/Xposed  (  844): Loading modules from /data/app/com.oasisfeng.google.maps.rectify-1/base.apk
11-03 12:23:38.657 I/Xposed  (  844):   Loading class com.oasisfeng.google.maps.rectify.GoogleMapsXposed
11-03 12:23:38.658 I/Xposed  (  844): Loading modules from /data/app/com.android.vending.billing.InAppBillingService.LOCK-1/base.apk
11-03 12:23:38.682 I/Xposed  (  844):   Loading class com.chelpus.XSupport
11-03 12:23:38.694 E/Xposed  (  844):     Failed to load class com.chelpus.XSupport
11-03 12:23:38.694 E/Xposed  (  844): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: java.util.jar.JarVerifier$VerifierEntry
11-03 12:23:38.694 E/Xposed  (  844): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
11-03 12:23:38.694 E/Xposed  (  844): 	at com.chelpus.XSupport.initZygote(XSupport.java:65)
11-03 12:23:38.694 E/Xposed  (  844): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:552)
11-03 12:23:38.694 E/Xposed  (  844): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:466)
11-03 12:23:38.694 E/Xposed  (  844): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:96)
11-03 12:23:38.694 E/Xposed  (  844): Caused by: java.lang.ClassNotFoundException: java.util.jar.JarVerifier$VerifierEntry
11-03 12:23:38.694 E/Xposed  (  844): 	at java.lang.Class.classForName(Native Method)
11-03 12:23:38.694 E/Xposed  (  844): 	at java.lang.Class.forName(Class.java:400)
11-03 12:23:38.694 E/Xposed  (  844): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
11-03 12:23:38.694 E/Xposed  (  844): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
11-03 12:23:38.694 E/Xposed  (  844): 	... 4 more
11-03 12:23:38.694 E/Xposed  (  844): Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.jar.JarVerifier$VerifierEntry" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/system/lib, /vendor/lib, /system/lib, /vendor/lib]]
11-03 12:23:38.694 E/Xposed  (  844): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-03 12:23:38.694 E/Xposed  (  844): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
11-03 12:23:38.694 E/Xposed  (  844): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-03 12:23:38.694 E/Xposed  (  844): 	... 8 more
11-03 12:23:38.694 I/Xposed  (  844): Loading modules from /data/app/com.fkzhang.wechatxposed-1/base.apk
11-03 12:23:38.711 I/Xposed  (  844):   Loading class com.fkzhang.wechatxposed.XposedInit
11-03 12:23:38.713 I/Xposed  (  844): Loading modules from /data/app/top.jowanxu.scanlogin-1/base.apk
11-03 12:23:38.729 I/Xposed  (  844):   Loading class top.jowanxu.scanlogin.Tutorial
11-03 12:23:38.730 E/Xposed  (  844):     Failed to load class top.jowanxu.scanlogin.Tutorial
11-03 12:23:38.730 E/Xposed  (  844): java.lang.ClassNotFoundException: Didn't find class "top.jowanxu.scanlogin.Tutorial" on path: DexPathList[[zip file "/data/app/top.jowanxu.scanlogin-1/base.apk"],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
11-03 12:23:38.730 E/Xposed  (  844): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-03 12:23:38.730 E/Xposed  (  844): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
11-03 12:23:38.730 E/Xposed  (  844): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-03 12:23:38.730 E/Xposed  (  844): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:536)
11-03 12:23:38.730 E/Xposed  (  844): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:466)
11-03 12:23:38.730 E/Xposed  (  844): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:96)
11-03 12:23:38.730 I/Xposed  (  844): Loading modules from /data/app/com.sinpo.nfcspy-1/base.apk
11-03 12:23:38.741 I/Xposed  (  844):   Loading class com.sinpo.nfcspy.XposedModApduRouting
11-03 12:24:08.043 I/Xposed  ( 3418): com.tencent.mm loading com.fkzhang.wechatxposed
11-03 12:24:20.029 I/Xposed  ( 3418): 微X模块 1.14_7.24(23,72) 1
11-03 12:24:20.446 I/Xposed  ( 3418): com.fkzhang.wechatxposed (1.14): wechat version 6.5.16(1120)

**Comment by Ive20** [comment]
麻烦作者了

**Comment by wangzailfm** [comment]
没事，我的xpose是88.1的，我等下下载88.2测试下。。

**Comment by wangzailfm** [comment]
我这边测试88.2都是正常的，你把模块卸载再重新安装试试

**Comment by Ive20** [comment]
我卸载安装重启了几次都还是不行.

**Comment by wangzailfm** [comment]
emmm，我再看看
